import numpy as np

def getSymmM(k, omega, nucleoFreqs):
    	symmMatrix = [[0 for x in range(61)] for x in range(61)] 

    	symmMatrix[0][1] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * omega  	#AAA->AAC: IS NonSynonymous
    	symmMatrix[0][2] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * k  	#AAA->AAG: IS Transition
    	symmMatrix[0][3] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * omega  	#AAA->AAT: IS NonSynonymous
    	symmMatrix[0][4] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * omega  	#AAA->ACA: IS NonSynonymous
    	symmMatrix[0][8] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * k * omega  	#AAA->AGA: IS TransitionIS NonSynonymous
    	symmMatrix[0][12] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * omega  	#AAA->ATA: IS NonSynonymous
    	symmMatrix[0][16] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * omega  	#AAA->CAA: IS NonSynonymous
    	symmMatrix[0][32] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * k * omega  	#AAA->GAA: IS TransitionIS NonSynonymous
    	symmMatrix[1][2] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * omega  	#AAC->AAG: IS NonSynonymous
    	symmMatrix[1][3] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * k  	#AAC->AAT: IS Transition
    	symmMatrix[1][5] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * omega  	#AAC->ACC: IS NonSynonymous
    	symmMatrix[1][9] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * k * omega  	#AAC->AGC: IS TransitionIS NonSynonymous
    	symmMatrix[1][13] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * omega  	#AAC->ATC: IS NonSynonymous
    	symmMatrix[1][17] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * omega  	#AAC->CAC: IS NonSynonymous
    	symmMatrix[1][33] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * k * omega  	#AAC->GAC: IS TransitionIS NonSynonymous
    	symmMatrix[1][48] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * omega  	#AAC->TAC: IS NonSynonymous
    	symmMatrix[2][3] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * omega  	#AAG->AAT: IS NonSynonymous
    	symmMatrix[2][6] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * omega  	#AAG->ACG: IS NonSynonymous
    	symmMatrix[2][10] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * k * omega  	#AAG->AGG: IS TransitionIS NonSynonymous
    	symmMatrix[2][14] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * omega  	#AAG->ATG: IS NonSynonymous
    	symmMatrix[2][18] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * omega  	#AAG->CAG: IS NonSynonymous
    	symmMatrix[2][34] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * k * omega  	#AAG->GAG: IS TransitionIS NonSynonymous
    	symmMatrix[3][7] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * omega  	#AAT->ACT: IS NonSynonymous
    	symmMatrix[3][11] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * k * omega  	#AAT->AGT: IS TransitionIS NonSynonymous
    	symmMatrix[3][15] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * omega  	#AAT->ATT: IS NonSynonymous
    	symmMatrix[3][19] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * omega  	#AAT->CAT: IS NonSynonymous
    	symmMatrix[3][35] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * k * omega  	#AAT->GAT: IS TransitionIS NonSynonymous
    	symmMatrix[3][49] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * omega  	#AAT->TAT: IS NonSynonymous
    	symmMatrix[4][5] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1])  	#ACA->ACC: 
    	symmMatrix[4][6] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * k  	#ACA->ACG: IS Transition
    	symmMatrix[4][7] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1])  	#ACA->ACT: 
    	symmMatrix[4][8] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * omega  	#ACA->AGA: IS NonSynonymous
    	symmMatrix[4][12] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * k * omega  	#ACA->ATA: IS TransitionIS NonSynonymous
    	symmMatrix[4][20] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#ACA->CCA: IS NonSynonymous
    	symmMatrix[4][36] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * k * omega  	#ACA->GCA: IS TransitionIS NonSynonymous
    	symmMatrix[4][50] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#ACA->TCA: IS NonSynonymous
    	symmMatrix[5][6] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1])  	#ACC->ACG: 
    	symmMatrix[5][7] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * k  	#ACC->ACT: IS Transition
    	symmMatrix[5][9] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * omega  	#ACC->AGC: IS NonSynonymous
    	symmMatrix[5][13] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * k * omega  	#ACC->ATC: IS TransitionIS NonSynonymous
    	symmMatrix[5][21] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * omega  	#ACC->CCC: IS NonSynonymous
    	symmMatrix[5][37] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * k * omega  	#ACC->GCC: IS TransitionIS NonSynonymous
    	symmMatrix[5][51] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * omega  	#ACC->TCC: IS NonSynonymous
    	symmMatrix[6][7] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1])  	#ACG->ACT: 
    	symmMatrix[6][10] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * omega  	#ACG->AGG: IS NonSynonymous
    	symmMatrix[6][14] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * k * omega  	#ACG->ATG: IS TransitionIS NonSynonymous
    	symmMatrix[6][22] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * omega  	#ACG->CCG: IS NonSynonymous
    	symmMatrix[6][38] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * k * omega  	#ACG->GCG: IS TransitionIS NonSynonymous
    	symmMatrix[6][52] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * omega  	#ACG->TCG: IS NonSynonymous
    	symmMatrix[7][11] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * omega  	#ACT->AGT: IS NonSynonymous
    	symmMatrix[7][15] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * k * omega  	#ACT->ATT: IS TransitionIS NonSynonymous
    	symmMatrix[7][23] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * omega  	#ACT->CCT: IS NonSynonymous
    	symmMatrix[7][39] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * k * omega  	#ACT->GCT: IS TransitionIS NonSynonymous
    	symmMatrix[7][53] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * omega  	#ACT->TCT: IS NonSynonymous
    	symmMatrix[8][9] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * omega  	#AGA->AGC: IS NonSynonymous
    	symmMatrix[8][10] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * k  	#AGA->AGG: IS Transition
    	symmMatrix[8][11] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * omega  	#AGA->AGT: IS NonSynonymous
    	symmMatrix[8][12] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * omega  	#AGA->ATA: IS NonSynonymous
    	symmMatrix[8][24] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0])  	#AGA->CGA: 
    	symmMatrix[8][40] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * k * omega  	#AGA->GGA: IS TransitionIS NonSynonymous
    	symmMatrix[9][10] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * omega  	#AGC->AGG: IS NonSynonymous
    	symmMatrix[9][11] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * k  	#AGC->AGT: IS Transition
    	symmMatrix[9][13] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * omega  	#AGC->ATC: IS NonSynonymous
    	symmMatrix[9][25] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * omega  	#AGC->CGC: IS NonSynonymous
    	symmMatrix[9][41] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * k * omega  	#AGC->GGC: IS TransitionIS NonSynonymous
    	symmMatrix[9][54] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * omega  	#AGC->TGC: IS NonSynonymous
    	symmMatrix[10][11] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * omega  	#AGG->AGT: IS NonSynonymous
    	symmMatrix[10][14] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * omega  	#AGG->ATG: IS NonSynonymous
    	symmMatrix[10][26] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2])  	#AGG->CGG: 
    	symmMatrix[10][42] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * k * omega  	#AGG->GGG: IS TransitionIS NonSynonymous
    	symmMatrix[10][55] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * omega  	#AGG->TGG: IS NonSynonymous
    	symmMatrix[11][15] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * omega  	#AGT->ATT: IS NonSynonymous
    	symmMatrix[11][27] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * omega  	#AGT->CGT: IS NonSynonymous
    	symmMatrix[11][43] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * k * omega  	#AGT->GGT: IS TransitionIS NonSynonymous
    	symmMatrix[11][56] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * omega  	#AGT->TGT: IS NonSynonymous
    	symmMatrix[12][13] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3])  	#ATA->ATC: 
    	symmMatrix[12][14] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * k * omega  	#ATA->ATG: IS TransitionIS NonSynonymous
    	symmMatrix[12][15] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3])  	#ATA->ATT: 
    	symmMatrix[12][28] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[0]) * omega  	#ATA->CTA: IS NonSynonymous
    	symmMatrix[12][44] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[0]) * k * omega  	#ATA->GTA: IS TransitionIS NonSynonymous
    	symmMatrix[12][57] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[0]) * omega  	#ATA->TTA: IS NonSynonymous
    	symmMatrix[13][14] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * omega  	#ATC->ATG: IS NonSynonymous
    	symmMatrix[13][15] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * k  	#ATC->ATT: IS Transition
    	symmMatrix[13][29] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * omega  	#ATC->CTC: IS NonSynonymous
    	symmMatrix[13][45] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * k * omega  	#ATC->GTC: IS TransitionIS NonSynonymous
    	symmMatrix[13][58] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * omega  	#ATC->TTC: IS NonSynonymous
    	symmMatrix[14][15] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * omega  	#ATG->ATT: IS NonSynonymous
    	symmMatrix[14][30] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * omega  	#ATG->CTG: IS NonSynonymous
    	symmMatrix[14][46] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * k * omega  	#ATG->GTG: IS TransitionIS NonSynonymous
    	symmMatrix[14][59] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * omega  	#ATG->TTG: IS NonSynonymous
    	symmMatrix[15][31] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#ATT->CTT: IS NonSynonymous
    	symmMatrix[15][47] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * k * omega  	#ATT->GTT: IS TransitionIS NonSynonymous
    	symmMatrix[15][60] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#ATT->TTT: IS NonSynonymous
    	symmMatrix[16][17] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#CAA->CAC: IS NonSynonymous
    	symmMatrix[16][18] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * k  	#CAA->CAG: IS Transition
    	symmMatrix[16][19] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#CAA->CAT: IS NonSynonymous
    	symmMatrix[16][20] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#CAA->CCA: IS NonSynonymous
    	symmMatrix[16][24] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * k * omega  	#CAA->CGA: IS TransitionIS NonSynonymous
    	symmMatrix[16][28] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#CAA->CTA: IS NonSynonymous
    	symmMatrix[16][32] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[0]) * omega  	#CAA->GAA: IS NonSynonymous
    	symmMatrix[17][18] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#CAC->CAG: IS NonSynonymous
    	symmMatrix[17][19] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * k  	#CAC->CAT: IS Transition
    	symmMatrix[17][21] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * omega  	#CAC->CCC: IS NonSynonymous
    	symmMatrix[17][25] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * k * omega  	#CAC->CGC: IS TransitionIS NonSynonymous
    	symmMatrix[17][29] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * omega  	#CAC->CTC: IS NonSynonymous
    	symmMatrix[17][33] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * omega  	#CAC->GAC: IS NonSynonymous
    	symmMatrix[17][48] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * k * omega  	#CAC->TAC: IS TransitionIS NonSynonymous
    	symmMatrix[18][19] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#CAG->CAT: IS NonSynonymous
    	symmMatrix[18][22] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * omega  	#CAG->CCG: IS NonSynonymous
    	symmMatrix[18][26] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * k * omega  	#CAG->CGG: IS TransitionIS NonSynonymous
    	symmMatrix[18][30] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * omega  	#CAG->CTG: IS NonSynonymous
    	symmMatrix[18][34] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[2]) * omega  	#CAG->GAG: IS NonSynonymous
    	symmMatrix[19][23] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * omega  	#CAT->CCT: IS NonSynonymous
    	symmMatrix[19][27] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * k * omega  	#CAT->CGT: IS TransitionIS NonSynonymous
    	symmMatrix[19][31] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * omega  	#CAT->CTT: IS NonSynonymous
    	symmMatrix[19][35] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * omega  	#CAT->GAT: IS NonSynonymous
    	symmMatrix[19][49] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * k * omega  	#CAT->TAT: IS TransitionIS NonSynonymous
    	symmMatrix[20][21] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1])  	#CCA->CCC: 
    	symmMatrix[20][22] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * k  	#CCA->CCG: IS Transition
    	symmMatrix[20][23] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1])  	#CCA->CCT: 
    	symmMatrix[20][24] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#CCA->CGA: IS NonSynonymous
    	symmMatrix[20][28] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * k * omega  	#CCA->CTA: IS TransitionIS NonSynonymous
    	symmMatrix[20][36] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#CCA->GCA: IS NonSynonymous
    	symmMatrix[20][50] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * k * omega  	#CCA->TCA: IS TransitionIS NonSynonymous
    	symmMatrix[21][22] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1])  	#CCC->CCG: 
    	symmMatrix[21][23] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * k  	#CCC->CCT: IS Transition
    	symmMatrix[21][25] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * omega  	#CCC->CGC: IS NonSynonymous
    	symmMatrix[21][29] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * k * omega  	#CCC->CTC: IS TransitionIS NonSynonymous
    	symmMatrix[21][37] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * omega  	#CCC->GCC: IS NonSynonymous
    	symmMatrix[21][51] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * k * omega  	#CCC->TCC: IS TransitionIS NonSynonymous
    	symmMatrix[22][23] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1])  	#CCG->CCT: 
    	symmMatrix[22][26] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * omega  	#CCG->CGG: IS NonSynonymous
    	symmMatrix[22][30] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * k * omega  	#CCG->CTG: IS TransitionIS NonSynonymous
    	symmMatrix[22][38] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * omega  	#CCG->GCG: IS NonSynonymous
    	symmMatrix[22][52] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * k * omega  	#CCG->TCG: IS TransitionIS NonSynonymous
    	symmMatrix[23][27] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * omega  	#CCT->CGT: IS NonSynonymous
    	symmMatrix[23][31] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * k * omega  	#CCT->CTT: IS TransitionIS NonSynonymous
    	symmMatrix[23][39] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * omega  	#CCT->GCT: IS NonSynonymous
    	symmMatrix[23][53] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * k * omega  	#CCT->TCT: IS TransitionIS NonSynonymous
    	symmMatrix[24][25] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2])  	#CGA->CGC: 
    	symmMatrix[24][26] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * k  	#CGA->CGG: IS Transition
    	symmMatrix[24][27] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2])  	#CGA->CGT: 
    	symmMatrix[24][28] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#CGA->CTA: IS NonSynonymous
    	symmMatrix[24][40] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * omega  	#CGA->GGA: IS NonSynonymous
    	symmMatrix[25][26] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2])  	#CGC->CGG: 
    	symmMatrix[25][27] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * k  	#CGC->CGT: IS Transition
    	symmMatrix[25][29] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * omega  	#CGC->CTC: IS NonSynonymous
    	symmMatrix[25][41] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * omega  	#CGC->GGC: IS NonSynonymous
    	symmMatrix[25][54] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * k * omega  	#CGC->TGC: IS TransitionIS NonSynonymous
    	symmMatrix[26][27] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2])  	#CGG->CGT: 
    	symmMatrix[26][30] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * omega  	#CGG->CTG: IS NonSynonymous
    	symmMatrix[26][42] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * omega  	#CGG->GGG: IS NonSynonymous
    	symmMatrix[26][55] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * k * omega  	#CGG->TGG: IS TransitionIS NonSynonymous
    	symmMatrix[27][31] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * omega  	#CGT->CTT: IS NonSynonymous
    	symmMatrix[27][43] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * omega  	#CGT->GGT: IS NonSynonymous
    	symmMatrix[27][56] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * k * omega  	#CGT->TGT: IS TransitionIS NonSynonymous
    	symmMatrix[28][29] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3])  	#CTA->CTC: 
    	symmMatrix[28][30] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * k  	#CTA->CTG: IS Transition
    	symmMatrix[28][31] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3])  	#CTA->CTT: 
    	symmMatrix[28][44] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[0]) * omega  	#CTA->GTA: IS NonSynonymous
    	symmMatrix[28][57] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[0]) * k  	#CTA->TTA: IS Transition
    	symmMatrix[29][30] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3])  	#CTC->CTG: 
    	symmMatrix[29][31] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * k  	#CTC->CTT: IS Transition
    	symmMatrix[29][45] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * omega  	#CTC->GTC: IS NonSynonymous
    	symmMatrix[29][58] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * k * omega  	#CTC->TTC: IS TransitionIS NonSynonymous
    	symmMatrix[30][31] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3])  	#CTG->CTT: 
    	symmMatrix[30][46] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * omega  	#CTG->GTG: IS NonSynonymous
    	symmMatrix[30][59] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * k  	#CTG->TTG: IS Transition
    	symmMatrix[31][47] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#CTT->GTT: IS NonSynonymous
    	symmMatrix[31][60] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * k * omega  	#CTT->TTT: IS TransitionIS NonSynonymous
    	symmMatrix[32][33] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * omega  	#GAA->GAC: IS NonSynonymous
    	symmMatrix[32][34] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * k  	#GAA->GAG: IS Transition
    	symmMatrix[32][35] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * omega  	#GAA->GAT: IS NonSynonymous
    	symmMatrix[32][36] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * omega  	#GAA->GCA: IS NonSynonymous
    	symmMatrix[32][40] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * k * omega  	#GAA->GGA: IS TransitionIS NonSynonymous
    	symmMatrix[32][44] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * omega  	#GAA->GTA: IS NonSynonymous
    	symmMatrix[33][34] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * omega  	#GAC->GAG: IS NonSynonymous
    	symmMatrix[33][35] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * k  	#GAC->GAT: IS Transition
    	symmMatrix[33][37] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * omega  	#GAC->GCC: IS NonSynonymous
    	symmMatrix[33][41] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * k * omega  	#GAC->GGC: IS TransitionIS NonSynonymous
    	symmMatrix[33][45] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * omega  	#GAC->GTC: IS NonSynonymous
    	symmMatrix[33][48] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[1]) * omega  	#GAC->TAC: IS NonSynonymous
    	symmMatrix[34][35] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * omega  	#GAG->GAT: IS NonSynonymous
    	symmMatrix[34][38] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * omega  	#GAG->GCG: IS NonSynonymous
    	symmMatrix[34][42] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * k * omega  	#GAG->GGG: IS TransitionIS NonSynonymous
    	symmMatrix[34][46] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * omega  	#GAG->GTG: IS NonSynonymous
    	symmMatrix[35][39] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * omega  	#GAT->GCT: IS NonSynonymous
    	symmMatrix[35][43] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * k * omega  	#GAT->GGT: IS TransitionIS NonSynonymous
    	symmMatrix[35][47] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * omega  	#GAT->GTT: IS NonSynonymous
    	symmMatrix[35][49] = 1.0 / (nucleoFreqs[0] * nucleoFreqs[3]) * omega  	#GAT->TAT: IS NonSynonymous
    	symmMatrix[36][37] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1])  	#GCA->GCC: 
    	symmMatrix[36][38] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * k  	#GCA->GCG: IS Transition
    	symmMatrix[36][39] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1])  	#GCA->GCT: 
    	symmMatrix[36][40] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * omega  	#GCA->GGA: IS NonSynonymous
    	symmMatrix[36][44] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * k * omega  	#GCA->GTA: IS TransitionIS NonSynonymous
    	symmMatrix[36][50] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[0]) * omega  	#GCA->TCA: IS NonSynonymous
    	symmMatrix[37][38] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1])  	#GCC->GCG: 
    	symmMatrix[37][39] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * k  	#GCC->GCT: IS Transition
    	symmMatrix[37][41] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * omega  	#GCC->GGC: IS NonSynonymous
    	symmMatrix[37][45] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * k * omega  	#GCC->GTC: IS TransitionIS NonSynonymous
    	symmMatrix[37][51] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[1]) * omega  	#GCC->TCC: IS NonSynonymous
    	symmMatrix[38][39] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1])  	#GCG->GCT: 
    	symmMatrix[38][42] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * omega  	#GCG->GGG: IS NonSynonymous
    	symmMatrix[38][46] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * k * omega  	#GCG->GTG: IS TransitionIS NonSynonymous
    	symmMatrix[38][52] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[2]) * omega  	#GCG->TCG: IS NonSynonymous
    	symmMatrix[39][43] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * omega  	#GCT->GGT: IS NonSynonymous
    	symmMatrix[39][47] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * k * omega  	#GCT->GTT: IS TransitionIS NonSynonymous
    	symmMatrix[39][53] = 1.0 / (nucleoFreqs[1] * nucleoFreqs[3]) * omega  	#GCT->TCT: IS NonSynonymous
    	symmMatrix[40][41] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2])  	#GGA->GGC: 
    	symmMatrix[40][42] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * k  	#GGA->GGG: IS Transition
    	symmMatrix[40][43] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2])  	#GGA->GGT: 
    	symmMatrix[40][44] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[0]) * omega  	#GGA->GTA: IS NonSynonymous
    	symmMatrix[41][42] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2])  	#GGC->GGG: 
    	symmMatrix[41][43] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * k  	#GGC->GGT: IS Transition
    	symmMatrix[41][45] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * omega  	#GGC->GTC: IS NonSynonymous
    	symmMatrix[41][54] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[1]) * omega  	#GGC->TGC: IS NonSynonymous
    	symmMatrix[42][43] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2])  	#GGG->GGT: 
    	symmMatrix[42][46] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * omega  	#GGG->GTG: IS NonSynonymous
    	symmMatrix[42][55] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[2]) * omega  	#GGG->TGG: IS NonSynonymous
    	symmMatrix[43][47] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * omega  	#GGT->GTT: IS NonSynonymous
    	symmMatrix[43][56] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * omega  	#GGT->TGT: IS NonSynonymous
    	symmMatrix[44][45] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3])  	#GTA->GTC: 
    	symmMatrix[44][46] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * k  	#GTA->GTG: IS Transition
    	symmMatrix[44][47] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3])  	#GTA->GTT: 
    	symmMatrix[44][57] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[0]) * omega  	#GTA->TTA: IS NonSynonymous
    	symmMatrix[45][46] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3])  	#GTC->GTG: 
    	symmMatrix[45][47] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3]) * k  	#GTC->GTT: IS Transition
    	symmMatrix[45][58] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * omega  	#GTC->TTC: IS NonSynonymous
    	symmMatrix[46][47] = 1.0 / (nucleoFreqs[2] * nucleoFreqs[3])  	#GTG->GTT: 
    	symmMatrix[46][59] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * omega  	#GTG->TTG: IS NonSynonymous
    	symmMatrix[47][60] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#GTT->TTT: IS NonSynonymous
    	symmMatrix[48][49] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[0]) * k  	#TAC->TAT: IS Transition
    	symmMatrix[48][51] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * omega  	#TAC->TCC: IS NonSynonymous
    	symmMatrix[48][54] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * k * omega  	#TAC->TGC: IS TransitionIS NonSynonymous
    	symmMatrix[48][58] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * omega  	#TAC->TTC: IS NonSynonymous
    	symmMatrix[49][53] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#TAT->TCT: IS NonSynonymous
    	symmMatrix[49][56] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * k * omega  	#TAT->TGT: IS TransitionIS NonSynonymous
    	symmMatrix[49][60] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#TAT->TTT: IS NonSynonymous
    	symmMatrix[50][51] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1])  	#TCA->TCC: 
    	symmMatrix[50][52] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * k  	#TCA->TCG: IS Transition
    	symmMatrix[50][53] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1])  	#TCA->TCT: 
    	symmMatrix[50][57] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[0]) * k * omega  	#TCA->TTA: IS TransitionIS NonSynonymous
    	symmMatrix[51][52] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1])  	#TCC->TCG: 
    	symmMatrix[51][53] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * k  	#TCC->TCT: IS Transition
    	symmMatrix[51][54] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * omega  	#TCC->TGC: IS NonSynonymous
    	symmMatrix[51][58] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * k * omega  	#TCC->TTC: IS TransitionIS NonSynonymous
    	symmMatrix[52][53] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1])  	#TCG->TCT: 
    	symmMatrix[52][55] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * omega  	#TCG->TGG: IS NonSynonymous
    	symmMatrix[52][59] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * k * omega  	#TCG->TTG: IS TransitionIS NonSynonymous
    	symmMatrix[53][56] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#TCT->TGT: IS NonSynonymous
    	symmMatrix[53][60] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * k * omega  	#TCT->TTT: IS TransitionIS NonSynonymous
    	symmMatrix[54][55] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * omega  	#TGC->TGG: IS NonSynonymous
    	symmMatrix[54][56] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * k  	#TGC->TGT: IS Transition
    	symmMatrix[54][58] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[1]) * omega  	#TGC->TTC: IS NonSynonymous
    	symmMatrix[55][56] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * omega  	#TGG->TGT: IS NonSynonymous
    	symmMatrix[55][59] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[2]) * omega  	#TGG->TTG: IS NonSynonymous
    	symmMatrix[56][60] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#TGT->TTT: IS NonSynonymous
    	symmMatrix[57][58] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#TTA->TTC: IS NonSynonymous
    	symmMatrix[57][59] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * k  	#TTA->TTG: IS Transition
    	symmMatrix[57][60] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#TTA->TTT: IS NonSynonymous
    	symmMatrix[58][59] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#TTC->TTG: IS NonSynonymous
    	symmMatrix[58][60] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * k  	#TTC->TTT: IS Transition
    	symmMatrix[59][60] = 1.0 / (nucleoFreqs[3] * nucleoFreqs[3]) * omega  	#TTG->TTT: IS NonSynonymous


    	#let lower triangle equal to upper
    	for i in range(61):
        	for j in range(61):
    		    	if i < j:
    			    	symmMatrix[j][i] = symmMatrix[i][j]

    	return symmMatrix

def getDiagM(nucleoFreqs):
    	diagMatrix = [0 for x in range(61)]

    	totalProb = 1.0 - nucleoFreqs[3] * nucleoFreqs[0] * nucleoFreqs[0] - nucleoFreqs[3] * nucleoFreqs[0] * nucleoFreqs[2] - nucleoFreqs[3] * nucleoFreqs[2] * nucleoFreqs[0]
    	
    	#example:
    	diagMatrix[0] = nucleoFreqs[0] * nucleoFreqs[0] * nucleoFreqs[0] / totalProb # AAA
    	diagMatrix[1] = nucleoFreqs[0] * nucleoFreqs[0] * nucleoFreqs[1] / totalProb # AAC
    	diagMatrix[2] = nucleoFreqs[0] * nucleoFreqs[0] * nucleoFreqs[2] / totalProb # AAG
    	diagMatrix[3] = nucleoFreqs[0] * nucleoFreqs[0] * nucleoFreqs[3] / totalProb # AAT
    	diagMatrix[4] = nucleoFreqs[0] * nucleoFreqs[1] * nucleoFreqs[0] / totalProb # ACA
    	diagMatrix[5] = nucleoFreqs[0] * nucleoFreqs[1] * nucleoFreqs[1] / totalProb # ACC
    	diagMatrix[6] = nucleoFreqs[0] * nucleoFreqs[1] * nucleoFreqs[2] / totalProb # ACG
    	diagMatrix[7] = nucleoFreqs[0] * nucleoFreqs[1] * nucleoFreqs[3] / totalProb # ACT
    	diagMatrix[8] = nucleoFreqs[0] * nucleoFreqs[2] * nucleoFreqs[0] / totalProb # AGA
    	diagMatrix[9] = nucleoFreqs[0] * nucleoFreqs[2] * nucleoFreqs[1] / totalProb # AGC
    	diagMatrix[10] = nucleoFreqs[0] * nucleoFreqs[2] * nucleoFreqs[2] / totalProb # AGG
    	diagMatrix[11] = nucleoFreqs[0] * nucleoFreqs[2] * nucleoFreqs[3] / totalProb # AGT
    	diagMatrix[12] = nucleoFreqs[0] * nucleoFreqs[3] * nucleoFreqs[0] / totalProb # ATA
    	diagMatrix[13] = nucleoFreqs[0] * nucleoFreqs[3] * nucleoFreqs[1] / totalProb # ATC
    	diagMatrix[14] = nucleoFreqs[0] * nucleoFreqs[3] * nucleoFreqs[2] / totalProb # ATG
    	diagMatrix[15] = nucleoFreqs[0] * nucleoFreqs[3] * nucleoFreqs[3] / totalProb # ATT
    	diagMatrix[16] = nucleoFreqs[1] * nucleoFreqs[0] * nucleoFreqs[0] / totalProb # CAA
    	diagMatrix[17] = nucleoFreqs[1] * nucleoFreqs[0] * nucleoFreqs[1] / totalProb # CAC
    	diagMatrix[18] = nucleoFreqs[1] * nucleoFreqs[0] * nucleoFreqs[2] / totalProb # CAG
    	diagMatrix[19] = nucleoFreqs[1] * nucleoFreqs[0] * nucleoFreqs[3] / totalProb # CAT
    	diagMatrix[20] = nucleoFreqs[1] * nucleoFreqs[1] * nucleoFreqs[0] / totalProb # CCA
    	diagMatrix[21] = nucleoFreqs[1] * nucleoFreqs[1] * nucleoFreqs[1] / totalProb # CCC
    	diagMatrix[22] = nucleoFreqs[1] * nucleoFreqs[1] * nucleoFreqs[2] / totalProb # CCG
    	diagMatrix[23] = nucleoFreqs[1] * nucleoFreqs[1] * nucleoFreqs[3] / totalProb # CCT
    	diagMatrix[24] = nucleoFreqs[1] * nucleoFreqs[2] * nucleoFreqs[0] / totalProb # CGA
    	diagMatrix[25] = nucleoFreqs[1] * nucleoFreqs[2] * nucleoFreqs[1] / totalProb # CGC
    	diagMatrix[26] = nucleoFreqs[1] * nucleoFreqs[2] * nucleoFreqs[2] / totalProb # CGG
    	diagMatrix[27] = nucleoFreqs[1] * nucleoFreqs[2] * nucleoFreqs[3] / totalProb # CGT
    	diagMatrix[28] = nucleoFreqs[1] * nucleoFreqs[3] * nucleoFreqs[0] / totalProb # CTA
    	diagMatrix[29] = nucleoFreqs[1] * nucleoFreqs[3] * nucleoFreqs[1] / totalProb # CTC
    	diagMatrix[30] = nucleoFreqs[1] * nucleoFreqs[3] * nucleoFreqs[2] / totalProb # CTG
    	diagMatrix[31] = nucleoFreqs[1] * nucleoFreqs[3] * nucleoFreqs[3] / totalProb # CTT
    	diagMatrix[32] = nucleoFreqs[2] * nucleoFreqs[0] * nucleoFreqs[0] / totalProb # GAA
    	diagMatrix[33] = nucleoFreqs[2] * nucleoFreqs[0] * nucleoFreqs[1] / totalProb # GAC
    	diagMatrix[34] = nucleoFreqs[2] * nucleoFreqs[0] * nucleoFreqs[2] / totalProb # GAG
    	diagMatrix[35] = nucleoFreqs[2] * nucleoFreqs[0] * nucleoFreqs[3] / totalProb # GAT
    	diagMatrix[36] = nucleoFreqs[2] * nucleoFreqs[1] * nucleoFreqs[0] / totalProb # GCA
    	diagMatrix[37] = nucleoFreqs[2] * nucleoFreqs[1] * nucleoFreqs[1] / totalProb # GCC
    	diagMatrix[38] = nucleoFreqs[2] * nucleoFreqs[1] * nucleoFreqs[2] / totalProb # GCG
    	diagMatrix[39] = nucleoFreqs[2] * nucleoFreqs[1] * nucleoFreqs[3] / totalProb # GCT
    	diagMatrix[40] = nucleoFreqs[2] * nucleoFreqs[2] * nucleoFreqs[0] / totalProb # GGA
    	diagMatrix[41] = nucleoFreqs[2] * nucleoFreqs[2] * nucleoFreqs[1] / totalProb # GGC
    	diagMatrix[42] = nucleoFreqs[2] * nucleoFreqs[2] * nucleoFreqs[2] / totalProb # GGG
    	diagMatrix[43] = nucleoFreqs[2] * nucleoFreqs[2] * nucleoFreqs[3] / totalProb # GGT
    	diagMatrix[44] = nucleoFreqs[2] * nucleoFreqs[3] * nucleoFreqs[0] / totalProb # GTA
    	diagMatrix[45] = nucleoFreqs[2] * nucleoFreqs[3] * nucleoFreqs[1] / totalProb # GTC
    	diagMatrix[46] = nucleoFreqs[2] * nucleoFreqs[3] * nucleoFreqs[2] / totalProb # GTG
    	diagMatrix[47] = nucleoFreqs[2] * nucleoFreqs[3] * nucleoFreqs[3] / totalProb # GTT
    	diagMatrix[48] = nucleoFreqs[3] * nucleoFreqs[0] * nucleoFreqs[1] / totalProb # TAC
    	diagMatrix[49] = nucleoFreqs[3] * nucleoFreqs[0] * nucleoFreqs[3] / totalProb # TAT
    	diagMatrix[50] = nucleoFreqs[3] * nucleoFreqs[1] * nucleoFreqs[0] / totalProb # TCA
    	diagMatrix[51] = nucleoFreqs[3] * nucleoFreqs[1] * nucleoFreqs[1] / totalProb # TCC
    	diagMatrix[52] = nucleoFreqs[3] * nucleoFreqs[1] * nucleoFreqs[2] / totalProb # TCG
    	diagMatrix[53] = nucleoFreqs[3] * nucleoFreqs[1] * nucleoFreqs[3] / totalProb # TCT
    	diagMatrix[54] = nucleoFreqs[3] * nucleoFreqs[2] * nucleoFreqs[1] / totalProb # TGC
    	diagMatrix[55] = nucleoFreqs[3] * nucleoFreqs[2] * nucleoFreqs[2] / totalProb # TGG
    	diagMatrix[56] = nucleoFreqs[3] * nucleoFreqs[2] * nucleoFreqs[3] / totalProb # TGT
    	diagMatrix[57] = nucleoFreqs[3] * nucleoFreqs[3] * nucleoFreqs[0] / totalProb # TTA
    	diagMatrix[58] = nucleoFreqs[3] * nucleoFreqs[3] * nucleoFreqs[1] / totalProb # TTC
    	diagMatrix[59] = nucleoFreqs[3] * nucleoFreqs[3] * nucleoFreqs[2] / totalProb # TTG
    	diagMatrix[60] = nucleoFreqs[3] * nucleoFreqs[3] * nucleoFreqs[3] / totalProb # TTT

    	return(diagMatrix)

def getRateM(k, omega, nucleoFreqs):
	symmM = getSymmM(k, omega, nucleoFreqs)
	diagM = getDiagM(nucleoFreqs)
	symmMatrix = np.array(symmM, dtype=float)
	diagMatrix = np.diag(diagM)
	root_distn = np.array(diagM, float)

	pre_Q = np.dot(symmMatrix, diagMatrix)
	#fill diagonal
	unnormalized_Q = pre_Q - np.diag(pre_Q.sum(axis=1))
	# Normalize the rate matrix so that branch lengths have the usual interpretation
	expected_rate = np.dot(root_distn, -np.diag(unnormalized_Q))
	#normalize to expected rate 1
	Q = unnormalized_Q / expected_rate
	
	return Q

if __name__ == "__main__":
	k = 2.1
	omega = 0.05
	nucleoFreqs = [0.21,0.29,0.12,0.38]
	print(getRateM(k, omega, nucleoFreqs))
